disable_tqdm: True
output_dir: "checkpoints"
evaluation_strategy: "epoch"
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5.0e-5
num_train_epochs: 10
seed: 42
save_strategy: "no"