disable_tqdm: True
output_dir: "checkpoints"
evaluation_strategy: "epoch"
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
num_train_epochs: 10
seed: 42
save_strategy: "no"
learning_rate: !!float 2e-5
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
warmup_steps: 10000
lr_scheduler_type: "linear"
gradient_accumulation_steps: 2