disable_tqdm: True
output_dir: "checkpoints"
evaluation_strategy: "epoch"
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
num_train_epochs: 10
seed: 42
save_strategy: "no"
learning_rate: 5e-5
weight_decay: 0.01
