disable_tqdm: True
output_dir: "checkpoints"
evaluation_strategy: "epoch"
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
num_train_epochs: 10
seed: 42
save_strategy: "epoch"
learning_rate: !!float 5e-5
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
warmup_steps: 10000
lr_scheduler_type: "linear"
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 10
seed: 42
save_strategy: "no"
load_best_model_at_end: True